apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:6dja8a7g/kgrZaOBFV3sJckaFNS77cS/fsxxKpat3yDXMRzMttnuNw==,iv:wEQjEDtObnMP3b+2RPMbMF7ol9lz+VGvhh5jB6NgEeM=,tag:rhZEvtTmqh7dAZaftiKNEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dk9xd0366s3nrwk820s6xthkp6xu3cewxy3ht2rvhzte6hsxyv6s2f7v9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGKy83dmY3eGdNSUVlZXly
            T3M0RGljQWxWdHBwaXFCcGk1dDhtRzM2VEVZCnhzOTY0aWdja2VPVDdiUjhabTFH
            VStIaGZxc0JGWnJvd1R0Y0QrWWhTWGcKLS0tIGNkVSt6SUFFTkVtOUdWUWZCa2dm
            YUlSTU9kZVM3d2c1VXdxSzVJclJoWHcK4e03/b2o9OVRZjpoBMeEz3R4Em0qQWBk
            zJ084Ch9TRORBa+shZgQv3qILOR9IQvLf4q4R6QG+4zgqTpsCIeoDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T09:09:06Z"
    mac: ENC[AES256_GCM,data:SIjWhZ6y8AA7kDK5BPNXKaGoaVAHa9Ccfa4MUoY8085I8ukNlwrXOonp/S4boDLS28XiMaptEXDgecczWsJl7Om6blpRzK3WiBrcrSdQncCwwJvrduj06JKkwd1X3ItIuPc1wKKsu3JG1s+YJocj3GKCgghXJsZvDF0IirsMKJ4=,iv:WNV6usiIY8MAzefuWu0jTUk/DHqH0ztKdbsiWFaWk7s=,tag:fU7YwNBZxnJvX5IPUK034w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
